name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Run unit tests
        run: |
          xcodebuild \
            -project KeyJig.xcodeproj \
            -scheme KeyJig \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            test
